# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapi', '0002_auto_20170614_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks', to='miapi.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='TrackRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=8)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='releasetracks', to='miapi.Release')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trackreleases', to='miapi.Track')),
            ],
        ),
        migrations.AlterField(
            model_name='userrelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userreleases', to='miapi.Release'),
        ),
        migrations.AlterField(
            model_name='userrelease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
