# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapi', '0003_auto_20170615_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userreleases', to=settings.AUTH_USER_MODEL),
        ),
    ]
